- hosts: localhost
  tasks:
  - name: delete old result
    file: path=/var/jenkins_home/workspace/robot/output.xml state=absent
  - name: delete old result
    file: path=/var/jenkins_home/workspace/robot/report.html state=absent
  - name: delete old result
    file: path=/var/jenkins_home/workspace/robot/log.html state=absent

- hosts: rfrun
  tasks:
  - name: copy test case
    copy: src=compass/devops dest=/app
  - name: create result directory
    file: path=/app/result state=directory
  - name: exec-dcetest
    shell: /usr/local/bin/robot --outputdir  /app/result /app/devops/测试用例/API.txt
  - name: fetch result
    fetch: src=/app/result/output.xml dest=/var/jenkins_home/workspace/robot flat=yes
  - name: fetch result
    fetch: src=/app/result/report.html dest=/var/jenkins_home/workspace/robot flat=yes
  - name: fetch result
    fetch: src=/app/result/log.html dest=/var/jenkins_home/workspace/robot flat=yes
